### ISSUE TITLE
11g-xe file not found on `vagrant up`

### ISSUE THREAD

**Issue by iovuio** [oracle/vagrant-boxes#108]
**Steps to reproduce**

1.  git clone https://github.com/oracle/vagrant-boxes/
2. cd vagrant-boxes/OracleDatabase/11.2.0.2
3. vagrant up

**Expected result**
    No errors during vagrant instalation.

**Actual result**
    2 errors encountered (1st and 3rd lines in following text):
```
    oracle11g-xe-vagrant: unzip:  cannot find or open /vagrant/oracle-xe-11.2.0-1.0.x86_64.rpm.zip, /vagrant/oracle-xe-11.2.0-1.0.x86_64.rpm.zip.zip or /vagrant/oracle-xe-11.2.0-1.0.x86_64.rpm.zip.ZIP.
    oracle11g-xe-vagrant: INSTALLER: Oracle software installed
    oracle11g-xe-vagrant: sudo: /etc/init.d/oracle-xe: command not found
```
Although those errors occur, `vagrant up` exits with code 0.

**Environment**
macOS Mojave 10.14.3
Vagrant 2.2.4
VirtualBox 6.0.4 r128413

**Comment by iovuio** [comment]
Same environment, same steps, fails for 12.2.0.1. More errors in the logs as below, still exits with code 0.

```
    oracle-12201-vagrant: unzip:  cannot find or open /vagrant/linux*122*.zip, /vagrant/linux*122*.zip.zip or /vagrant/linux*122*.zip.ZIP.
    oracle-12201-vagrant:
    oracle-12201-vagrant: No zipfiles found.
    oracle-12201-vagrant: -bash: /vagrant/database/runInstaller: No such file or directory
    oracle-12201-vagrant: /tmp/vagrant-shell: line 61: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory
    oracle-12201-vagrant: /tmp/vagrant-shell: line 62: /opt/oracle/product/12.2.0.1/dbhome_1/root.sh: No such file or directory
    oracle-12201-vagrant: INSTALLER: Oracle software installed
    oracle-12201-vagrant: -bash: lsnrctl: command not found
    oracle-12201-vagrant: INSTALLER: Listener created
    oracle-12201-vagrant: -bash: dbca: command not found
    oracle-12201-vagrant: -bash: sqlplus: command not found
    oracle-12201-vagrant: INSTALLER: Database created
    oracle-12201-vagrant: sed: can't read /etc/oratab: No such file or directory
    oracle-12201-vagrant: INSTALLER: Oratab configured
    oracle-12201-vagrant: Created symlink from /etc/systemd/system/multi-user.target.wants/oracle-rdbms.service to /etc/systemd/system/oracle-rdbms.service.
    oracle-12201-vagrant: Job for oracle-rdbms.service failed because the control process exited with error code. See "systemctl status oracle-rdbms.service" and "journalctl -xe" for details.
```
